build(release): update release script

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,8 +1,23 @@
 #!/bin/bash
 
-VERSION=$(npm version patch)
+REQUIRED_TOOLS=(
+  npm
+  git
+)
+
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
+
+RELEASE=${1:-patch}
+npm version "${RELEASE}"
+VERSION_SEM=$(node -p "require('./package').version")
+NAME=$(node -p "require('./package').name")
 git add package*
-git commit -m "chore(release): release ${VERSION}"
-git tag "${VERSION}"
+git commit -m "chore(release): release ${NAME}@${VERSION_SEM}"
+git tag "${NAME}@${VERSION_SEM}"
 npm publish
 git push origin --tags
